version: "3"
services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: firstprojectnest
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - dbtest

  db:
    build: .docker/postgres
    container_name: firstprojectnest-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres

  dbtest:
    build: .docker/postgres
    container_name: firstprojectnest-dbtest
    restart: always
    tty: true
    ports:
      - "5433:5432"
    volumes:
      - .docker/dbdatatest:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=testdb
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: firstprojectnest-pgadmin
    tty: true
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db